baseURL = 'https://marcinpendolski.pl'
title = 'Strona główna'
theme = 'congo'
defaultContentLanguage = 'pl'

[languages]
  [languages.pl]
    languageCode = 'pl-pl'
    languageName = 'Polski'
    weight = 1


# Congo wymaga wyjścia JSON dla poprawnego działania wbudowanej wyszukiwarki
[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "dracula"

[params]
  # Estetyka i kolorystyka (slate = nowoczesny, techniczny grafit)
  colorScheme = "slate"
  showAppearanceToggle = true # Przełącznik trybu ciemnego/jasnego
  showScrollToTop = true

# Konfiguracja nagłówka (flex umieszcza logo/nazwę po lewej, a menu po prawej)
[params.header]
  layout = "flex"

# Aktywacja układu graficznej wizytówki na stronie głównej
[params.homepage]
  layout = "profile"

# Dane profilowe autora wyświetlane na stronie głównej
[params.author]
  name = "Marcin Pendolski"
  image = "profile.jpg" # Plik należy umieścić w folderze: assets/profile.jpg
  headline = "Analityk Danych | AI, Customer Experience i Optymalizacja Procesów | Contact Center | Python | SQL | Power BI"
  bio = "Zapraszam do kontaktu i wymiany doświadczeń w obszarze Data & AI!"
  tocTitle = "Spis treści"
  links = [
    { email = "mailto:marcin.pendolski@gmail.com" },
    { linkedin = "https://linkedin.com/in/marcinpendolski" },
    { github = "https://github.com/PendolM" }
  ]

# Ustawienia artykułów (wygodne dla wpisów technicznych i kodu)
[params.article]
  showCodeCopyButton = true   # Przycisk "Kopiuj" przy blokach kodu (np. Python)
  showTableOfContents = true  # Spis treści (TOC) boczny/przyklejony
  showBreadcrumbs = true      # Ścieżka nawigacji na górze wpisu
  showReadingTime = true      # Szacowany czas czytania
  showDate = true             # Data publikacji

# Wbudowana wyszukiwarka w nagłówku
[params.search]
  enable = true
  showInHeader = true

# Główne menu nawigacyjne (będzie wyrównane do prawej dzięki nagłówkowi flex)

[[menu.main]]
  name = "O mnie"
  url = "/o_mnie/"
  weight = 10

[[menu.main]]
  name = "LinkedIn"
  url = "/posts/"
  weight = 20

[[menu.main]]
  name = "Analizy"
  url = "/anal/"
  weight = 30

[[menu.main]]
  name = "Aplikacje"
  url = "/app/"
  weight = 40
